### ISSUE TITLE
Changes to character history for the stone mask overflow

### ISSUE THREAD

**Issue by backwardsEric** [Cryomaniac13/hengband-touhou-katteban-en#23]
clang warns about these translations overflowing the 60 characters each history line can hold:

1. cmd3.c line 1056 "However, one day you got possessed by Ninja Soul from Heian era!"
2. cmd3.c line 1062 "You have only one goal: Take revenge on the moon goddess Chang'e!"
3. cmd3.c line 1065 "You have only one goal: Take revenge on the Serpent of Chaos!
4. cmd3.c line 1071 "You have only one goal: Take revenge on those who have oppressed you!"
5. cmd3.c line 1074 "You have only one goal: Take revenge on all of the Lords of Amber!"
6. cmd3.c line 1699 "However, one day you got possessed by Ninja Soul from Heian era!"
7. cmd3.c line 1705 "You have only one goal: Take revenge on the moon goddess Chang'e!"
8. cmd3.c line 1708 "You have only one goal: Take revenge on the Serpent of Chaos!"
9. cmd3.c line 1714 "You have only one goal: Take revenge on those who have oppressed you!")
10. cmd3.c line 1717 "You have only one goal: Take revenge on all of the Lords of Amber!"

**Comment by Cryomaniac13** [comment]
Should be fixed by https://github.com/Cryomaniac13/hengband-touhou-katteban-en/commit/bb93a1529c4d669b0b4241de34b7259635016891 and https://github.com/Cryomaniac13/hengband-touhou-katteban-en/commit/9c855c64a8d85fb528b647a1c11f13fbdabd25f6
