### ISSUE TITLE
Changing defeated unique character status from 'Dead' to 'Defeated' in the known monsters menu

### ISSUE THREAD

**Issue by miu135** [Cryomaniac13/hengband-touhou-katteban-en#32]
I know this is really minor but is it possible to change the unique monster statuses that were already defeated to just 'defeated' instead of 'dead' in the known monsters menu?

**Comment by Cryomaniac13** [comment]
Thanks for noticing that, I thought I replaced all instances of that wording. Will be fixed in next release.

**Comment by Cryomaniac13** [comment]
Fixed, wording will be changed to 'defeated' or 'active' in next release. This was a problem with my translation - JP version already didn't imply killing.
