### ISSUE TITLE
Miyoi can't complete quests requiring you to eliminate enemies

### ISSUE THREAD

**Issue by miu135** [Cryomaniac13/hengband-touhou-katteban-en#33]
Due to the 'signature dish' skill technically not killing your enemies, quests with elimination objectives cannot be completed.

**Comment by Cryomaniac13** [comment]
The author of the original JP version was informed of this issue and said it's going to be fixed. Since I'm only maintaining the English translation, this problem will be fixed when the corresponding update will be available for JP sources.

**Comment by Cryomaniac13** [comment]
Fixed in v2.0.9b; English translation is ready as well
