### ISSUE TITLE
Nue needs to change map to re-unidentify

### ISSUE THREAD

**Issue by Z8PNKbbY** [Cryomaniac13/hengband-touhou-katteban-en#35]
Once Nue is identified, the unidentified transformation won't be reapplied until entering a new floor. This behaviour doesn't happen in JP 2.0.10; killing/removing the offending monsters works as expected.
May be related to the Nue bugfixes back in 2.0.5.
(Tried making a post on oook about this, seems to be stuck in approval)

**Comment by Cryomaniac13** [comment]
That's my fault, I missed some non-critical changes to v2.0.5 source code; I added them and made a commit, will release updated build later on

**Comment by Cryomaniac13** [comment]
Released new binary with the fix; behaviour should be correct now
