### ISSUE TITLE
Koa-confusion

### ISSUE THREAD

**Issue by Z8PNKbbY** [Cryomaniac13/hengband-touhou-katteban-en#47]
In #45, I changed the name of the "Small Demon" ego to "Imp" without considering the Implications. The imp monster is インプ but the Imp race and the ego are 小悪魔.
Gensouband follows the multiple-Koakumas fanon, using 小悪魔 as both a proper noun and a common noun. There's intentionally no distinction between koakuma (race) and Koakuma (character).

Therefore I suggest:
- Changing both the "Small demon" monster and the "Imp" race to "Koakuma", disconnecting them from imp and generic demon monsters.
- Changing the "of the Imp" ego to "of the Little Devil", as that's the most commonly used literal translation in English, and it preserves the naming style of egos. Also "devil" is almost exclusively associated with Koumakan characters in this variant (as opposed to demon which is everywhere).

Although the same thing is true with greater fairy/Daiyousei, Daiyousei is always treated as an individual, never as a generic mob like Koakuma sometimes is (are?), so I feel like that should be left alone.

**Comment by Cryomaniac13** [comment]
I actually was going to name the race 'Koakuma' at the very start of translation; going to change the names now if you also agree it fits better. I'm still keeping 'Greater fairy' - fairies are also a separate class of enemies in this variant, so the naming should be kept consistent. Koakuma is one of a kind in this case - other demons/devils are from Hengband/earlier variants.

**Comment by Cryomaniac13** [comment]
Changed names/descriptions in new commit.
