### ISSUE TITLE
"Konparo"/"Konbaro" minutia

### ISSUE THREAD

**Issue by Z8PNKbbY** [Cryomaniac13/hengband-touhou-katteban-en#50]
An editor on thpatch.net has identified Medicine's コンパロ as a typo of コンバロ, from コンバラトキシン (convallatoxin).

This is a bit awkward as Gensouband corrects typos in some other quoted lines but not this one. It also makes pretty much zero difference to an English reader either way, and very little difference to even a Japanese reader. I don't know what the Japanese community thinks about it, or if it's worth changing or not.

**Comment by Cryomaniac13** [comment]
Seems that JP community also associates 'Konparo' spelling with Medicine; I'm leaving it as it is.
